# Generated by Django 4.2.6 on 2023-10-31 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('proofOfId', models.ImageField(blank=True, default='', null=True, upload_to='photos/proofOfID')),
                ('guarantorName', models.CharField(blank=True, max_length=250, null=True)),
                ('BankAccountDetails', models.TextField(blank=True, max_length=250, null=True)),
                ('guarantorPhoneNumber', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agentuser', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agentuserprofile', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+!~-*', length=10, max_length=40, prefix='OOLPC_', primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tat_limit', models.CharField(max_length=50)),
                ('unit_rate_within_tat', models.CharField(max_length=50)),
                ('unit_rate_outside_tat', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+!~-*', length=10, max_length=40, prefix='OOLP_', unique=True)),
                ('clientJobrefID', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('0', 'Undone'), ('1', 'Done'), ('2', 'Rejected')], default='0', max_length=100)),
                ('published', models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Yes')], default='1', max_length=100, null=True)),
                ('whenAssigned', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('BATCH_NO', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='staffs.agent')),
                ('assignedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(default='', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='staffs.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('clientJobrefID',)},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobRefNo', models.CharField(blank=True, max_length=250, null=True)),
                ('clientJobrefID', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('Client', models.CharField(blank=True, max_length=250, null=True)),
                ('VerificationMessage', models.CharField(choices=[('Incomplete Information', 'Incomplete Information'), ('No Response at the Address', 'No Response at the Address'), ('Address Does Not Exist', 'Address Does Not Exist'), ('Security Agents prevented access to Address', 'Security Agents prevented access to Address'), ('Address is an empty plot of Land', 'Address is an empty plot of Land'), ('The Customer has relocated', 'The Customer has relocated'), ('The Customer is not known at the address', 'The Customer is not known at the address'), ('The Customer is known but does not reside in the premises', 'The Customer is known but does not reside in the premises'), ('Address exists and customer is known', 'Address exists and customer is known'), ('Customer does not live at the address but visits often', 'Customer does not live at the address but visits often'), ('The Customer is deceased', 'The Customer is deceased'), ('The Customer works at the address but does not reside there', 'The Customer works at the address but does not reside there'), ('Customer was met at a different house number', 'Customer was met at a different house number'), ('Address is customers family house and does not reside there', 'Address is customers family house and does not reside there'), ('Company is not known at the address', 'Company is not known at the address'), ('Company is known and operate from the address', 'Company is known and operate from the address'), ('Could not locate address', 'Could not locate address'), ('Incomplete address', 'Incomplete address')], max_length=250)),
                ('agent', models.CharField(max_length=250)),
                ('address', models.TextField(blank=True, null=True)),
                ('Reportstatus', models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Rejected')], default='0', max_length=250, null=True)),
                ('buildingCondition', models.CharField(blank=True, choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed'), ('N/A', 'N/A')], max_length=250, null=True)),
                ('buildingColor', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('buildingType', models.CharField(blank=True, choices=[('Bungalow', 'Bungalow'), ('Storey Building', 'Storey Building'), ('Duplex', 'Duplex'), ('Block of flat', 'Block of flat'), ('BQ', 'BQ'), ('Multiple Floors', 'Multiple Floors'), ('Terrace', 'Terrace'), ('N/A', 'N/A')], default='', max_length=250, null=True)),
                ('CustomerRelationshipWithaddress', models.CharField(blank=True, choices=[('Landlord', 'Landlord'), ('Tenant', 'Tenant'), ('None', 'None'), ('N/A', 'N/A')], max_length=250, null=True)),
                ('AddressResidential', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='', max_length=250, null=True)),
                ('NameofindividualInterviewed', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('RelationshipWithCustomer', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('MoreComment', models.TextField(blank=True, default='', max_length=250, null=True)),
                ('Landmark', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('photo1', models.ImageField(blank=True, default='', null=True, upload_to='photos/address_pictures')),
                ('photo2', models.ImageField(blank=True, default='', null=True, upload_to='photos/address_pictures')),
                ('TAT', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='staffs.job', to_field='ref_no')),
            ],
            options={
                'unique_together': {('customer',)},
            },
        ),
    ]
