# Generated by Django 4.2.6 on 2023-12-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='customerName',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
