# Generated by Django 4.2.6 on 2023-12-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_report_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_report_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
