# Generated by Django 4.2.6 on 2023-12-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_report_pdf_report_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_report_link',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
