# Generated by Django 4.2.6 on 2023-12-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_alter_report_pdf_report_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='pdf_report_link',
        ),
    ]
