# Generated by Django 4.2 on 2025-06-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_report_formatted_address_report_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='formatted_address',
        ),
    ]
