# Generated by Django 4.2 on 2025-06-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0009_remove_report_formatted_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='saved',
            field=models.BooleanField(default=False, help_text='Flag indicating this report was partially saved (lat/long only)'),
        ),
    ]
